"""add set effort tracking

Revision ID: 99024e5be72e
Revises: 94011204cb00
Create Date: 2026-09-02 13:23:33.717196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99024e5be72e'
down_revision: Union[str, Sequence[str], None] = '94011204cb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('rpe', sa.Float(), nullable=True))
    op.add_column('workout_sets', sa.Column('rir', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'rir')
    op.drop_column('workout_sets', 'rpe')
    # ### end Alembic commands ###
